[package]
name = "dnsbl-dm"
version = "0.1.0"
authors = ["Colm Hickey <colmohici@gmail.com>"]

[dependencies]
rustc-serialize = "0.3"
c-ares = "0.19.0"
nix = "0.6.0"

[dependencies.zmq]
git = "https://github.com/erickt/rust-zmq.git"
